package com.github.misterchangray.dao.mapper;

import com.github.misterchangray.dao.entity.BusinessLog;
import com.github.misterchangray.dao.entity.BusinessLogQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessLogMapper {
    long countByQuery(BusinessLogQuery query);

    int deleteByQuery(BusinessLogQuery query);

    int deleteByPrimaryKey(Integer id);

    int insert(BusinessLog record);

    int insertSelective(BusinessLog record);

    List<BusinessLog> selectByQuery(BusinessLogQuery query);

    BusinessLog selectByPrimaryKey(Integer id);

    int updateByQuerySelective(@Param("record") BusinessLog record, @Param("example") BusinessLogQuery query);

    int updateByQuery(@Param("record") BusinessLog record, @Param("example") BusinessLogQuery query);

    int updateByPrimaryKeySelective(BusinessLog record);

    int updateByPrimaryKey(BusinessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<BusinessLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<BusinessLog> list, @Param("selective") BusinessLog.Column ... selective);
}