package com.github.misterchangray.dao.mapper;

import com.github.misterchangray.dao.entity.Constant;
import com.github.misterchangray.dao.entity.ConstantQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstantMapper {
    long countByQuery(ConstantQuery query);

    int deleteByQuery(ConstantQuery query);

    int deleteByPrimaryKey(Integer id);

    int insert(Constant record);

    int insertSelective(Constant record);

    List<Constant> selectByQuery(ConstantQuery query);

    Constant selectByPrimaryKey(Integer id);

    int updateByQuerySelective(@Param("record") Constant record, @Param("example") ConstantQuery query);

    int updateByQuery(@Param("record") Constant record, @Param("example") ConstantQuery query);

    int updateByPrimaryKeySelective(Constant record);

    int updateByPrimaryKey(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Constant> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Constant> list, @Param("selective") Constant.Column ... selective);
}