package com.github.misterchangray.dao.mapper;

import com.github.misterchangray.dao.entity.LoginLog;
import com.github.misterchangray.dao.entity.LoginLogQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginLogMapper {
    long countByQuery(LoginLogQuery query);

    int deleteByQuery(LoginLogQuery query);

    int deleteByPrimaryKey(Integer id);

    int insert(LoginLog record);

    int insertSelective(LoginLog record);

    List<LoginLog> selectByQuery(LoginLogQuery query);

    LoginLog selectByPrimaryKey(Integer id);

    int updateByQuerySelective(@Param("record") LoginLog record, @Param("example") LoginLogQuery query);

    int updateByQuery(@Param("record") LoginLog record, @Param("example") LoginLogQuery query);

    int updateByPrimaryKeySelective(LoginLog record);

    int updateByPrimaryKey(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<LoginLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<LoginLog> list, @Param("selective") LoginLog.Column ... selective);
}