package com.github.misterchangray.dao.mapper;

import com.github.misterchangray.dao.entity.OperationLog;
import com.github.misterchangray.dao.entity.OperationLogQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationLogMapper {
    long countByQuery(OperationLogQuery query);

    int deleteByQuery(OperationLogQuery query);

    int deleteByPrimaryKey(Integer id);

    int insert(OperationLog record);

    int insertSelective(OperationLog record);

    List<OperationLog> selectByQueryWithBLOBs(OperationLogQuery query);

    List<OperationLog> selectByQuery(OperationLogQuery query);

    OperationLog selectByPrimaryKey(Integer id);

    int updateByQuerySelective(@Param("record") OperationLog record, @Param("example") OperationLogQuery query);

    int updateByQueryWithBLOBs(@Param("record") OperationLog record, @Param("example") OperationLogQuery query);

    int updateByQuery(@Param("record") OperationLog record, @Param("example") OperationLogQuery query);

    int updateByPrimaryKeySelective(OperationLog record);

    int updateByPrimaryKeyWithBLOBs(OperationLog record);

    int updateByPrimaryKey(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<OperationLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<OperationLog> list, @Param("selective") OperationLog.Column ... selective);
}