package com.github.misterchangray.dao.mapper;

import com.github.misterchangray.dao.entity.Role;
import com.github.misterchangray.dao.entity.RoleQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    long countByQuery(RoleQuery query);

    int deleteByQuery(RoleQuery query);

    int deleteByPrimaryKey(Integer id);

    int insert(Role record);

    int insertSelective(Role record);

    List<Role> selectByQuery(RoleQuery query);

    Role selectByPrimaryKey(Integer id);

    int updateByQuerySelective(@Param("record") Role record, @Param("example") RoleQuery query);

    int updateByQuery(@Param("record") Role record, @Param("example") RoleQuery query);

    int updateByPrimaryKeySelective(Role record);

    int updateByPrimaryKey(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Role> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Role> list, @Param("selective") Role.Column ... selective);
}