package com.github.misterchangray.dao.mapper;

import com.github.misterchangray.dao.entity.RolePermissionMap;
import com.github.misterchangray.dao.entity.RolePermissionMapQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapMapper {
    long countByQuery(RolePermissionMapQuery query);

    int deleteByQuery(RolePermissionMapQuery query);

    int deleteByPrimaryKey(Integer id);

    int insert(RolePermissionMap record);

    int insertSelective(RolePermissionMap record);

    List<RolePermissionMap> selectByQuery(RolePermissionMapQuery query);

    RolePermissionMap selectByPrimaryKey(Integer id);

    int updateByQuerySelective(@Param("record") RolePermissionMap record, @Param("example") RolePermissionMapQuery query);

    int updateByQuery(@Param("record") RolePermissionMap record, @Param("example") RolePermissionMapQuery query);

    int updateByPrimaryKeySelective(RolePermissionMap record);

    int updateByPrimaryKey(RolePermissionMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<RolePermissionMap> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<RolePermissionMap> list, @Param("selective") RolePermissionMap.Column ... selective);
}