package com.github.misterchangray.dao.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="com.github.misterchangray.dao.entity.Constant")
public class Constant {
    @ApiModelProperty(value="id")
    private Integer id;

    @ApiModelProperty(value="name常量名称")
    private String name;

    @ApiModelProperty(value="shortcut常量简称,用于快速定位")
    private String shortcut;

    @ApiModelProperty(value="pid父ID,null为根节点")
    private Integer pid;

    @ApiModelProperty(value="level当前层级;pid=null时为1级")
    private Integer level;

    @ApiModelProperty(value="hasChild是否有子节点0false,1true")
    private Integer hasChild;

    @ApiModelProperty(value="enabled是否启用0false,1true")
    private Integer enabled;

    @ApiModelProperty(value="deleted是否删除0false, 1true")
    private Integer deleted;

    @ApiModelProperty(value="extra附加数据;推荐存JSON")
    private Integer extra;

    public Integer getId() {
        return id;
    }

    public Constant setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public Constant setName(String name) {
        this.name = name == null ? null : name.trim();
        return this;
    }

    public String getShortcut() {
        return shortcut;
    }

    public Constant setShortcut(String shortcut) {
        this.shortcut = shortcut == null ? null : shortcut.trim();
        return this;
    }

    public Integer getPid() {
        return pid;
    }

    public Constant setPid(Integer pid) {
        this.pid = pid;
        return this;
    }

    public Integer getLevel() {
        return level;
    }

    public Constant setLevel(Integer level) {
        this.level = level;
        return this;
    }

    public Integer getHasChild() {
        return hasChild;
    }

    public Constant setHasChild(Integer hasChild) {
        this.hasChild = hasChild;
        return this;
    }

    public Integer getEnabled() {
        return enabled;
    }

    public Constant setEnabled(Integer enabled) {
        this.enabled = enabled;
        return this;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public Constant setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    public Integer getExtra() {
        return extra;
    }

    public Constant setExtra(Integer extra) {
        this.extra = extra;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", shortcut=").append(shortcut);
        sb.append(", pid=").append(pid);
        sb.append(", level=").append(level);
        sb.append(", hasChild=").append(hasChild);
        sb.append(", enabled=").append(enabled);
        sb.append(", deleted=").append(deleted);
        sb.append(", extra=").append(extra);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table constant
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        name("name"),
        shortcut("shortcut"),
        pid("pid"),
        level("level"),
        hasChild("has_child"),
        enabled("enabled"),
        deleted("deleted"),
        extra("extra");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table constant
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table constant
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table constant
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table constant
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table constant
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table constant
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}