package com.github.misterchangray.dao.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="com.github.misterchangray.dao.entity.Permission")
public class Permission {
    @ApiModelProperty(value="id")
    private Integer id;

    @ApiModelProperty(value="name")
    private String name;

    @ApiModelProperty(value="deleted是否删除0false, 1true")
    private Integer deleted;

    @ApiModelProperty(value="uri")
    private String uri;

    @ApiModelProperty(value="type1菜单2按钮")
    private Integer type;

    @ApiModelProperty(value="puri")
    private String puri;

    public Integer getId() {
        return id;
    }

    public Permission setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public Permission setName(String name) {
        this.name = name == null ? null : name.trim();
        return this;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public Permission setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    public String getUri() {
        return uri;
    }

    public Permission setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
        return this;
    }

    public Integer getType() {
        return type;
    }

    public Permission setType(Integer type) {
        this.type = type;
        return this;
    }

    public String getPuri() {
        return puri;
    }

    public Permission setPuri(String puri) {
        this.puri = puri == null ? null : puri.trim();
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", deleted=").append(deleted);
        sb.append(", uri=").append(uri);
        sb.append(", type=").append(type);
        sb.append(", puri=").append(puri);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        name("name"),
        deleted("deleted"),
        uri("uri"),
        type("type"),
        puri("puri");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}