package com.github.misterchangray.dao.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="com.github.misterchangray.dao.entity.User")
public class User {
    @ApiModelProperty(value="id")
    private Integer id;

    @ApiModelProperty(value="username用户名")
    private String username;

    @ApiModelProperty(value="password密码")
    private String password;

    @ApiModelProperty(value="idcard身份证")
    private String idcard;

    @ApiModelProperty(value="email邮箱")
    private String email;

    @ApiModelProperty(value="name姓名")
    private String name;

    @ApiModelProperty(value="sex性别")
    private Integer sex;

    @ApiModelProperty(value="phone手机号")
    private String phone;

    @ApiModelProperty(value="enabled是否启用0false，1true")
    private Integer enabled;

    @ApiModelProperty(value="deleted是否删除0false，1true")
    private Integer deleted;

    public Integer getId() {
        return id;
    }

    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getUsername() {
        return username;
    }

    public User setUsername(String username) {
        this.username = username == null ? null : username.trim();
        return this;
    }

    public String getPassword() {
        return password;
    }

    public User setPassword(String password) {
        this.password = password == null ? null : password.trim();
        return this;
    }

    public String getIdcard() {
        return idcard;
    }

    public User setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
        return this;
    }

    public String getEmail() {
        return email;
    }

    public User setEmail(String email) {
        this.email = email == null ? null : email.trim();
        return this;
    }

    public String getName() {
        return name;
    }

    public User setName(String name) {
        this.name = name == null ? null : name.trim();
        return this;
    }

    public Integer getSex() {
        return sex;
    }

    public User setSex(Integer sex) {
        this.sex = sex;
        return this;
    }

    public String getPhone() {
        return phone;
    }

    public User setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
        return this;
    }

    public Integer getEnabled() {
        return enabled;
    }

    public User setEnabled(Integer enabled) {
        this.enabled = enabled;
        return this;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public User setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", idcard=").append(idcard);
        sb.append(", email=").append(email);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", phone=").append(phone);
        sb.append(", enabled=").append(enabled);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        username("username"),
        password("password"),
        idcard("idcard"),
        email("email"),
        name("name"),
        sex("sex"),
        phone("phone"),
        enabled("enabled"),
        deleted("deleted");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}