package com.zr.dao.mapper;

import com.zr.dao.entity.UserRoleMap;
import com.zr.dao.entity.UserRoleMapQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapMapper {
    long countByQuery(UserRoleMapQuery query);

    int deleteByQuery(UserRoleMapQuery query);

    int deleteByPrimaryKey(Integer id);

    int insert(UserRoleMap record);

    int insertSelective(UserRoleMap record);

    List<UserRoleMap> selectByQuery(UserRoleMapQuery query);

    UserRoleMap selectByPrimaryKey(Integer id);

    int updateByQuerySelective(@Param("record") UserRoleMap record, @Param("example") UserRoleMapQuery query);

    int updateByQuery(@Param("record") UserRoleMap record, @Param("example") UserRoleMapQuery query);

    int updateByPrimaryKeySelective(UserRoleMap record);

    int updateByPrimaryKey(UserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<UserRoleMap> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<UserRoleMap> list, @Param("selective") UserRoleMap.Column ... selective);
}